name: function重复检查
on:
  push:
    paths:
      - '**.postfixTemplates'
  workflow_dispatch:
jobs:
  function_name_check_job:
    name: function name check job
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: set node version
        uses: actions/setup-node@v4
      - run: echo 'github.action_path = ${{github.action_path}}'
      - name: install dep
        run: npm install glob
      - name: run check
        run: node ./.github/scripts/function_dup_check.js
