name: Function重复检查
on:
  push:
  workflow_dispatch:
jobs:
  function_name_check_job:
    name: function name check job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: .github/scripts

      - name: Run duplicate function check
        run: node .github/scripts/function_dup_check.mjs
        working-directory: ${{ github.workspace }}
